name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        arch: [ x86_64, x86 ]
    runs-on: windows-latest
    concurrency: release

    permissions:
      id-token: write
      contents: write

    steps:
      # Note: we need to checkout the repository at the workflow sha in case during the workflow
      # the branch was updated. To keep PSR working with the configured release branches,
      # we force a checkout of the desired release branch but at the workflow sha HEAD.
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup | Install Inno Setup & UPX & 7-Zip
        run: choco install innosetup upx 7zip -y

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          changelog: true
          github_token: ${{ secrets.GH_PAT }}
          git_committer_name: ${{vars.GH_USERNAME}}
          git_committer_email: ${{vars.GH_EMAIL}}

      - name: Build | Build PowerToysRunEnhance
        id: build
        env:
          NEW_VERSION: ${{ steps.release.outputs.version }}
          GITHUB_ACTIONS: "true"
          ARCH: ${{ matrix.arch }}
          PYTHON: "cpython-3.12.9-windows-${{matrix.arch}}-none"
        run: .\scripts\build.ps1


      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.21.0
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GH_PAT }}
          tag: ${{ steps.release.outputs.tag }}

